### PR TITLE
Add off-diagonal contribution to the thermal conductivity in BTE solver

### PR DESCRIPTION
**Pull request by OrbitalC**
Add the off-diagonal contribution to the thermal_conductivity binary using the formulation from the Quasi-Harmonic Green Kubo.
More specifically, I used added the off diagonal contribution from eq.(23) and (24) from [Fiorentino et al, Phys. Rev. B 107 054311](https://doi.org/10.1103/PhysRevB.107.054311)

To compute the generalized group velocities, I copied the routines from src/lineshape/lo_thermal_transport.f90

With this contribution, now the log looks like (it's from silicon, so the off diagonal contribution is not really important)
``` Temperature: 300.00000
 iter         kxx            kyy            kzz            kxy            kxz            kyz       DeltaF/F
    0        94.6973        94.6973        94.6973         0.0000         0.0000         0.0000
    1       100.5430       100.5436       100.5436         0.0000         0.0000         0.0000   0.453E+00
    2       102.7022       102.7028       102.7028         0.0000         0.0000         0.0000   0.241E-02
    3       103.0762       103.0769       103.0768         0.0000         0.0000         0.0000   0.234E-03
    4       103.1730       103.1736       103.1736         0.0000         0.0000         0.0000   0.536E-05
    5       103.1923       103.1930       103.1929         0.0000         0.0000         0.0000   0.450E-06
            103.1970       103.1976       103.1976         0.0000         0.0000         0.0000
 Off diagonal contribution
              kxx            kyy            kzz            kxy            kxz            kyz   
              0.0023         0.0023         0.0023         0.0000         0.0001         0.0000
 Total kappa (W/m/K)
              kxx            kyy            kzz            kxy            kxz            kyz   
            103.1993       103.2000       103.1999         0.0000         0.0001         0.0000 ```

### CODE REVIEW

**Comment by flokno** [comment]
Thanks @OrbitalC !

Questions:
- [ ] "offdiagonal" is in the sense of mode space, right? Is it the same as Peierls vs coherent transport in the Simoncelli language? Or what are the differences?
- [ ] why is the `kxz` nonzero in the offdiagonal case?

**Comment by OrbitalC** [comment]
Yes, it's the coherent or tunelling transport from Simoncelli papers. It's also what's called off-diagonal in lineshape so I kept the same name.
For the non zero kxz, it looks like it's due the low k-point grid I used for this test (a 4x4x4). When you increase the grid it goes to zero

In my local branch I made a slight modification to speed up the computation of this term, and I also did something to decompose the different contribution to kappa in the log, where I print everything as
```  Temperature: 300.00000
 iter         kxx            kyy            kzz            kxy            kxz            kyz       DeltaF/F
    0       113.5583       113.5583       113.5583         0.0000         0.0000         0.0000
    1       120.1317       120.1318       120.1318         0.0000         0.0000         0.0000   0.550E+00
    2       122.9874       122.9875       122.9875         0.0000         0.0000         0.0000   0.243E-02
    3       123.4095       123.4095       123.4095         0.0000         0.0000         0.0000   0.176E-02
    4       123.5480       123.5480       123.5480         0.0000         0.0000         0.0000   0.505E-05
    5       123.5705       123.5706       123.5706         0.0000         0.0000         0.0000   0.593E-06
            123.5776       123.5777       123.5777         0.0000         0.0000         0.0000
 Single mode approximation (W/m/K)
              kxx            kyy            kzz            kxy            kxz            kyz   
            113.5583       113.5583       113.5583         0.0000         0.0000         0.0000
 Dressed bubble correction (W/m/K)
              kxx            kyy            kzz            kxy            kxz            kyz   
             10.0194        10.0194        10.0194         0.0000         0.0000         0.0000
 Off diagonal contribution (W/m/K)
              kxx            kyy            kzz            kxy            kxz            kyz   
              0.0041         0.0041         0.0041         0.0000         0.0000         0.0000
 Total kappa (W/m/K)
              kxx            kyy            kzz            kxy            kxz            kyz   
            123.5817       123.5818       123.5818         0.0000         0.0000         0.0000```

(Same system, but 16x16x16 kpoint grid to show that the off diagonal kxz term becomes 0)
(Dressed bubble correction is the correction from the iterative Boltzman equation - I can give it an other name if it's better)

Should I keep this decomposition of go as before ?

**Comment by flokno** [comment]
@OrbitalC yes I think the decomposition is great.

2 further suggestions:

- [ ] Make ` Off diagonal contribution (W/m/K)` ` Off diagonal (coherent) contribution (W/m/K)`
- [ ] Maybe references, like ` Off diagonal contribution (W/m/K) [1]` and below add the references? I think it's very easy to loose track of what's been computed and what do cite eventually

**Comment by OrbitalC** [comment]
I really like the idea of adding references, I think we should add some for every binary, just before the timing prints

With the modification, the output looks like 

``` Temperature: 300.00000
 iter         kxx            kyy            kzz            kxy            kxz            kyz       DeltaF/F
    0        60.4938        60.4938        60.4938         0.0000         0.0000         0.0000
    1        61.6782        61.6806        61.6813        -0.0008         0.0008         0.0004   0.309E+00
    2        62.8733        62.8753        62.8756        -0.0008         0.0008         0.0000   0.651E-03
    3        63.0208        63.0229        63.0233        -0.0008         0.0008         0.0000   0.698E-04
    4        63.0643        63.0664        63.0668        -0.0008         0.0008         0.0000   0.170E-05
    5        63.0720        63.0741        63.0744        -0.0008         0.0008         0.0000   0.109E-06
             63.0738        63.0759        63.0762        -0.0008         0.0008         0.0000
 Single mode approximation (W/m/K)
              kxx            kyy            kzz            kxy            kxz            kyz   
             60.4938        60.4938        60.4938         0.0000         0.0000         0.0000
 Dressed bubble correction (W/m/K)
              kxx            kyy            kzz            kxy            kxz            kyz   
              2.5800         2.5821         2.5824        -0.0008         0.0008         0.0000
 Off diagonal (coherent) contribution (W/m/K)
              kxx            kyy            kzz            kxy            kxz            kyz   
              0.0010         0.0010         0.0010         0.0000         0.0000         0.0000
 Total kappa (W/m/K)
              kxx            kyy            kzz            kxy            kxz            kyz   
             63.0747        63.0768        63.0772        -0.0008         0.0008         0.0000
 
 Suggested citations :
                           Software : F. Knoop et al., J. Open Source Softw 9(94), 6150 (2024)
                             Method : D. A. Broido et al., Appl Phys Lett 91, 231922 (2007)
                          Algorithm : A. H. Romero et al., Phys Rev B 91, 214310 (2015)
 Off diagonal coherent contribution : L. Isaeva et al., Nat Commun 10 3853 (2019
                                      A. Fiorentino et al., Phys Rev B 107 054311 (2023)

**Comment by OrbitalC** [comment]
The `kxy` that appears during the IBTE where there before.
Though they usually disappear when increasing the qpoint grid.
The same happens with the off-diagonal coherent thermal conductivity both here and within lineshape.

It looks like a numerical problem, and maybe we could add a function to clean the thermal conductivity tensors and impose the symmetries.
This would also help to ensure that terms in the tensor that should be equivalent are indeed, as it's something that can also happen with the IBTE.
But it also get better with this problem when increasing the qpoint grid.

**Comment by OrbitalC** [comment]
For example, using the current main branch, still silicon, same force constants and setting 100K to enhance the importance of the IBTE I get

with a 3x3x3 grid
``` 81.5218        81.8771        81.7062        -0.0747         0.0747        -0.0854```

with a 12x12x12 grid
``` 430.9780       430.9814       430.9830        -0.0033         0.0039         0.0000```

with a 16x16x16
```466.5043       466.5062       466.5067        -0.0026         0.0030         0.0000```

and if I continue increasing (but I'm on my laptop here) the off diagonal term becomes negligible and the symmetry gets better.
But I think that problem needs its own issue.

**Comment by flokno** [comment]
Ok good.

Can you describe this briefly in the docs? https://github.com/tdep-developers/tdep/blob/main/docs/program/thermal_conductivity.md

Like which equation in which reference the output refers to, probably with a comment why coherent contributions in TDEP are likely smaller compared to what Michele is doing

**Comment by OrbitalC** [comment]
Done !
Except for the why it should be smaller in TDEP. I have a hand wavy explanation of why, but not really adequate for the documentation.
Do you have an idea on what you want to be said about this ?

**Comment by flokno** [comment]
I think it's a good opportunity to fix the broken doc string for `outfile.thermal_conductivity`, see https://github.com/OrbitalC/tdep/pull/1

**Review by flokno — DISMISSED** [review]

**Review by flokno — APPROVED** [review]
good, thanks!

**Pull request merged**
